Repository MatthewFuchs/Ogopogo-Tech, pull requests merged in 2024-03, with the labels that each got.

#35 Backend creation and initial user routes set up
  .gitignore
  backend/app.js
  backend/routes/userRoutes.js
  backend/server.js
  backend/test/userRoutes.test.js
  package-lock.json
  package.json
Labels: enhancement

#44 added design pattern documentation
  Requirements/COSC310 M3 - Design Pattern.pdf
Labels: documentation

#45 42 mongodb database integration
  backend/app.js
  backend/server.js
  package-lock.json
  package.json
Labels: enhancement

#57 Completed user registration functionality
  backend/app.js
  backend/controller/userController.js
  backend/models/userModel.js
  backend/models/userSchema.js
  backend/routes/userRoutes.js
  package-lock.json
  package.json
Labels: enhancement

#61 user tests updated to reflect current login and registration functionality
  backend/test/userRoutes.test.js
Labels: testing

#73 Add files via upload
  frontend/about.html
  frontend/contact.html
  frontend/courses.html
  frontend/css/about.css
  frontend/css/contact.css
  frontend/css/courses.css
  frontend/css/index.css
  frontend/css/log-in.css
  frontend/css/profile.css
  frontend/css/sign-up.css
  frontend/index.html
  frontend/log-in.html
  frontend/profile.html
  frontend/scripts/script.js
  frontend/sign-up.html
Labels: enhancement

#76 Added create-course.html and admin.css
  frontend/create-course.html
  frontend/css/admin.css
  frontend/scripts/admin.js
Labels: enhancement

#82 Added new field to add course instructor, updated admin.css to match …
  frontend/create-course.html
  frontend/css/admin.css
Labels: documentation, update

#88 Link user registration login with frontend
  backend/app.js
  frontend/sign-up.html
  package-lock.json
  package.json
Labels: update

#94 87 implement database schema for assignment management
  backend/app.js
  backend/controller/assignmentController.js
  backend/models/assignmentModel.js
  backend/routes/assignmentRoutes.js
  backend/test/controllers/assignmentController.test.js
  backend/test/models/assignmentModel.test.js
  backend/test/models/courseModel.test.js
  backend/test/routes/assignmentRoutes.test.js
  frontend/css/index.css
Labels: back_end, Assignment Management

#92 Completed frontend for user details update along with the backend functionality
  backend/controller/userController.js
  backend/middleware/authMiddleware.js
  backend/routes/userRoutes.js
  backend/test/userRoutes.test.js
  frontend/log-in.html
  frontend/profile.html
  frontend/scripts/login.js
  frontend/scripts/profile.js
  frontend/scripts/script.js
  frontend/scripts/update-user.js
  frontend/sign-up.html
  frontend/update-user.html
Labels: enhancement

#102 fixed bug
  backend/controller/userController.js
  backend/routes/userRoutes.js
  frontend/css/profile.css
  frontend/profile.html
  frontend/scripts/profile.js
  frontend/scripts/update-user.js
  frontend/update-user.html
  package-lock.json
  package.json
Labels: bug

#101 Changed Homepage
  auth.js
  index.css
  index.html
Labels: bug, enhancement, help wanted, front_end

#106 Added model, route and controller for Assignment
  backend/app.js
  backend/controller/assignmentController.js
  backend/models/assignmentModel.js
  backend/routes/assignmentRoutes.js
  package-lock.json
Labels: enhancement, back_end

#111 finished enrollment tests
  backend/app.js
  backend/test/enrollment.test.js
Labels: testing

#120 Weeks 1-6 scrum records
  Scrum Meeting/SCRUM-MEETING-1.docx
  Scrum Meeting/SCRUM-MEETING-2.docx
  Scrum Meeting/SCRUM-MEETING-3.docx
  Scrum Meeting/SCRUM-MEETING-4.docx
  Scrum Meeting/SCRUM-MEETING-5.docx
  Scrum Meeting/SCRUM-MEETING-6.docx
Labels: documentation

#122 121 integrate frontend with backend for assignment update view submission
  backend/app.js
  backend/controller/assignmentController.js
  backend/models/assignmentModel.js
  backend/routes/assignmentRoutes.js
  frontend/assignments-list-student.html
  frontend/assignments-list.html
  frontend/create-assignment.html
  frontend/css/assignment.css
  frontend/do-assignment.html
  frontend/modify-assignment.html
  frontend/submitted-assignment.html
Labels: front_end, back_end, Assignment Management
